minecraft_version_range=[1.20.1,)
forge_version=47.4.10
forge_version_range=[47.4,)
loader_version_range=[47,)

neoForge.parchment.minecraftVersion=1.20.1
neoForge.parchment.mappingsVersion=2023.09.03

minecraft_resource_format=15

jaopca_version_id=4742609
ae2_version=15.2.15

glodium_version_id=5226922
extendedae_version_id=6010405

immersiveengineering_version_id=6206989
mekanism_version_id=6552911
jei_version_id=8419086
