plugins {
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.gradle.userdev' version '7.0.170'
}

group = mod_group_id
version = mod_version

java {
    archivesBaseName = 'JAOPCAExtras-' + minecraft_version
    toolchain.languageVersion = JavaLanguageVersion.of(21)
}

runs {
    configureEach {
        workingDirectory project.file("run/${it.name}")
        systemProperty 'forge.logging.markers', 'REGISTRIES'
        systemProperty 'forge.logging.console.level', 'debug'

        modSource project.sourceSets.main
    }

    client {
        systemProperty 'neoforge.enabledGameTestNamespaces', 'jaopcaextras'
    }

    server {
        systemProperty 'neoforge.enabledGameTestNamespaces', 'jaopcaextras'
        argument '--nogui'
    }

    gameTestServer {
        systemProperty 'neoforge.enabledGameTestNamespaces', 'jaopcaextras'
    }

    data {
        arguments.addAll '--mod', 'jaopcaextras', '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    maven {
        url "https://cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
    maven {
        url "https://maven.blamejared.com/"
        content {
            includeGroup "mezz.jei"
        }
    }
    maven {
        url "https://modmaven.dev/"
        content {
            includeGroup "appeng"
        }
    }
    maven {
        url "https://maven.tterrag.com/"
        content {
            includeGroup "com.simibubi.create"
        }
    }
}

dependencies {
    implementation "net.neoforged:neoforge:${neo_version}"
//    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'

    implementation "curse.maven:jaopca-266936:5842919"

    implementation "mezz.jei:jei-1.21.1-neoforge:19.21.0.247"

    implementation "org.appliedenergistics:appliedenergistics2:19.2.4"
    // runtimeOnly fg.deobf("curse.maven:lazierae2-489843:4145521")

    // for debug
//    runtimeOnly fg.deobf("curse.maven:cofh-69162:4385216")
//    runtimeOnly fg.deobf("curse.maven:thermalfoundation-222880:4382373")
//    runtimeOnly fg.deobf("curse.maven:thermalexpansion-69163:4382371")
//    runtimeOnly fg.deobf("mekanism:Mekanism:1.19.2-10.3.8.477")
//    runtimeOnly fg.deobf("com.simibubi.create:create-1.20.1:0.5.1.d-9:all") {
//        transitive = false
//    }
//    runtimeOnly "curse.maven:ato-405593:6118610"
    runtimeOnly "curse.maven:immersiveengineering-231951:6418024"
}

jar {
    manifest {
        attributes([
                "Specification-Title"     : "JAOPCAExtras",
                "Specification-Vendor"    : "BlueSheep2804",
                "Specification-Version"   : "1", // We are version 1 of ourselves
                "Implementation-Title"    : project.name,
                "Implementation-Version"  : project.jar.archiveVersion,
                "Implementation-Vendor"   : "BlueSheep2804",
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version: neo_version,
            neo_version_range: neo_version_range,
            loader_version_range: loader_version_range,
            mod_id: mod_id,
            mod_name: mod_name,
            mod_version: mod_version
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}
