modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "MIT"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "BlueSheep2804"
description = "Mod to add various modules to JAOPCA."

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "jaopca"
type = "required"
versionRange = "[5.0.4.5,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "ae2"
type = "optional"
versionRange = "[19.2.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "jei"
type = "optional"
versionRange = "[19.21.0.0,)"
ordering = "AFTER"
side = "BOTH"
